package logging

/*
Copyright 2022 The k8gb Contributors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

Generated by GoLic, for more details see: https://github.com/AbsaOSS/golic
*/

import (
	"fmt"
	"os"
	"sync"
	"time"

	"pnpay.io/internal/cli"

	"github.com/rs/zerolog"
	"github.com/rs/zerolog/pkgerrors"
)

var (
	once sync.Once
	log  zerolog.Logger
)

// Logger public static logger, providing instance of initialised logger
func Logger() *zerolog.Logger {
	return &log
}

// Init always initialise logger, no mif config is nil or not
func Init(c *cli.Config) {
	once.Do(func() {
		log = getLogger(c)
	})
}

// getManagementEntities returns new logger even if it doesn't know level or format.
// In such case returns default logger
func getLogger(l *cli.Config) zerolog.Logger {
	var logger zerolog.Logger
	if l.Log.Format == cli.NoFormat {
		l.Log.Format = cli.SimpleFormat
	}
	if l.Log.Level == zerolog.NoLevel {
		l.Log.Level = zerolog.InfoLevel
	}
	// We can retrieve stack in case of pkg/errors
	zerolog.ErrorStackMarshaler = pkgerrors.MarshalStack
	zerolog.SetGlobalLevel(l.Log.Level)
	switch l.Log.Format {
	case cli.JSONFormat:
		logger = zerolog.New(os.Stdout).
			With().
			Caller().
			Timestamp().
			Logger().
			Level(l.Log.Level)
	case cli.SimpleFormat:
		logger = zerolog.New(zerolog.ConsoleWriter{Out: os.Stderr, TimeFormat: time.RFC3339, NoColor: l.Log.NoColor}).
			With().
			Caller().
			Timestamp().
			Logger().
			Level(l.Log.Level)
	}
	logger.Info().Msg("Logger configured")
	logger.Info().
		Str("format", fmt.Sprintf("%s", l.Log.Format)). // nolint:gosimple
		Str("level", l.Log.Level.String()).
		Msg("Logger settings")
	return logger
}

func GetDefaultLogger() *zerolog.Logger {
	l := getLogger(&cli.Config{Log: cli.Log{
		Level:   zerolog.InfoLevel,
		Format:  cli.SimpleFormat,
		NoColor: true,
	}})
	return &l
}
