# https://taskfile.dev/usage/
---
version: '3'

# env:
#   LOCALBIN: /bin
#   TFENV_TERRAFORM_VERSION: 1.5.7

# dotenv: ['.env']

tasks:
  lint:
    cmds:
      - gitleaks detect . --no-git --verbose --config=.gitleaks.toml
      - yamllint .
      - goimports -w ./
      - $GOBIN/golangci-lint run -c .golangci.yaml
      - go test $(go list ./... | grep -Ev '/v1') -coverprofile cover.out

  lint-init:
    cmds:
      - brew install gitleaks
      - brew install yamllint

  mocks:
    cmds:
      - go install go.uber.org/mock/mockgen@v0.4.0
      - mockgen -package=mocks -destination=internal/mocks/crud_mock.go -source=internal/provider.go Provider
      - mockgen -package=mocks -destination=internal/mocks/providers_mock.go -source=internal/providers.go Providers
      # go.uber.org/mock v0.5.0
